name: Test News Scraper

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test imports and basic functionality
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from main import NewsScraper
        
        # Test basic initialization
        scraper = NewsScraper()
        print('✅ NewsScraper initialized successfully')
        
        # Test database initialization
        scraper.init_db()
        print('✅ Database initialized successfully')
        
        # Test site configuration
        sites = scraper._get_sites()
        print(f'✅ Found {len(sites)} configured sites')
        
        scraper.db.close()
        print('✅ All tests passed!')
        "
        
    - name: Test without API keys (dry run)
      env:
        NEWS_SITE_1: "https://pedal.ir"
        NEWS_SITE_2: "https://www.motor1.com"
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from main import NewsScraper
        
        scraper = NewsScraper()
        
        # Test news collection without API
        print('Testing news collection...')
        news = scraper.get_news_titles('https://pedal.ir')
        print(f'✅ Collected {len(news)} news items from test site')
        
        scraper.db.close()
        print('✅ Dry run completed successfully!')
        "